// PosLite is a self-contained extension (no cross-project imports per
// CLAUDE.md) — this is a minimal AR/FR/EN string table covering only the
// keys this till's UI uses.

export type Lang = 'fr' | 'ar' | 'en';

export const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  fr: {
    pos: 'Point de vente',
    search: 'Rechercher...',
    allItems: 'Tous les articles',
    loading: 'Chargement…',
    stock: 'Stock',
    cart: 'Panier',
    cartEmpty: 'Votre panier est vide.',
    total: 'Total',
    checkout: 'Payer',
    confirmPayment: 'Confirmer le paiement',
    checkoutProcessing: 'Traitement…',
    cash: 'Espèces',
    card: 'Carte',
    paymentMethod: 'Mode de paiement',
    amountPaid: 'Montant payé',
    changeDue: 'Monnaie à rendre',
    shortBy: 'Manquant',
    amountDue: 'Montant dû',
    close: 'Fermer',
    saleComplete: 'Vente terminée',
    online: 'En ligne',
    offline: 'Hors ligne',
    queued: 'en attente',
    fullySynced: 'Synchronisé',
    syncing: 'Synchro',
    syncNow: 'Synchroniser',
    failedSales: 'Ventes en échec',
    retry: 'Réessayer',
    noFailedSales: 'Aucune vente en échec',
    login: 'Connexion',
    username: 'Nom d\'utilisateur',
    password: 'Mot de passe',
    invalidCredentials: 'Identifiants invalides',
    receiptNo: 'Reçu N°',
    cashier: 'Caissier',
    date: 'Date',
    time: 'Heure',
    qtyAbbrev: 'Qté',
    unitPrice: 'Prix unit.',
    invoiceItem: 'Article',
    totalAmount: 'Total',
    receiptFooter: 'Merci de votre visite !',
    settings: 'Paramètres',
    theme: 'Thème',
    light: 'Clair',
    dark: 'Sombre',
    language: 'Langue',
    serverOnlineBlock: 'Le serveur est en ligne. Veuillez utiliser le point de vente principal.',
    serverUrl: 'URL du serveur',
    printAgentUrl: 'URL de l\'agent d\'impression',
    printAgentUrlHint: 'Laisser vide sur les tablettes (sans imprimante).',
    save: 'Enregistrer',
    settingsSaved: 'Paramètres enregistrés',
  },
  ar: {
    pos: 'نقطة البيع',
    search: 'بحث...',
    allItems: 'جميع المنتجات',
    loading: 'جارٍ التحميل…',
    stock: 'المخزون',
    cart: 'السلة',
    cartEmpty: 'سلتك فارغة.',
    total: 'الإجمالي',
    checkout: 'دفع',
    confirmPayment: 'تأكيد الدفع',
    checkoutProcessing: 'جارٍ المعالجة…',
    cash: 'نقداً',
    card: 'بطاقة',
    paymentMethod: 'طريقة الدفع',
    amountPaid: 'المبلغ المدفوع',
    changeDue: 'الباقي',
    shortBy: 'الناقص',
    amountDue: 'المبلغ المستحق',
    close: 'إغلاق',
    saleComplete: 'تمت عملية البيع',
    online: 'متصل',
    offline: 'غير متصل',
    queued: 'قيد الانتظار',
    fullySynced: 'متزامن',
    syncing: 'مزامنة',
    syncNow: 'مزامنة الآن',
    failedSales: 'مبيعات فاشلة',
    retry: 'إعادة المحاولة',
    noFailedSales: 'لا توجد مبيعات فاشلة',
    login: 'تسجيل الدخول',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    invalidCredentials: 'بيانات الدخول غير صحيحة',
    receiptNo: 'رقم الإيصال',
    cashier: 'الكاشير',
    date: 'التاريخ',
    time: 'الوقت',
    qtyAbbrev: 'كمية',
    unitPrice: 'سعر الوحدة',
    invoiceItem: 'المنتج',
    totalAmount: 'الإجمالي',
    receiptFooter: 'شكراً لزيارتكم!',
    settings: 'الإعدادات',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    language: 'اللغة',
    serverOnlineBlock: 'الخادم متصل. يرجى استخدام نقطة البيع الرئيسية.',
    serverUrl: 'رابط الخادم',
    printAgentUrl: 'رابط وكيل الطباعة',
    printAgentUrlHint: 'اتركه فارغاً على الأجهزة اللوحية (بدون طابعة).',
    save: 'حفظ',
    settingsSaved: 'تم حفظ الإعدادات',
  },
  en: {
    pos: 'Point of Sale',
    search: 'Search...',
    allItems: 'All Items',
    loading: 'Loading…',
    stock: 'Stock',
    cart: 'Cart',
    cartEmpty: 'Your cart is empty.',
    total: 'Total',
    checkout: 'Checkout',
    confirmPayment: 'Confirm Payment',
    checkoutProcessing: 'Processing…',
    cash: 'Cash',
    card: 'Card',
    paymentMethod: 'Payment Method',
    amountPaid: 'Amount Paid',
    changeDue: 'Change Due',
    shortBy: 'Short By',
    amountDue: 'Amount Due',
    close: 'Close',
    saleComplete: 'Sale Complete',
    online: 'Online',
    offline: 'Offline',
    queued: 'queued',
    fullySynced: 'Fully synced',
    syncing: 'Syncing',
    syncNow: 'Sync now',
    failedSales: 'Failed Sales',
    retry: 'Retry',
    noFailedSales: 'No failed sales',
    login: 'Login',
    username: 'Username',
    password: 'Password',
    invalidCredentials: 'Invalid credentials',
    receiptNo: 'Receipt #',
    cashier: 'Cashier',
    date: 'Date',
    time: 'Time',
    qtyAbbrev: 'Qty',
    unitPrice: 'Unit Price',
    invoiceItem: 'Item',
    totalAmount: 'Total',
    receiptFooter: 'Thank you for your visit!',
    settings: 'Settings',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    serverOnlineBlock: 'Server is online. Please use the main POS.',
    serverUrl: 'Server URL',
    printAgentUrl: 'Print Agent URL',
    printAgentUrlHint: 'Leave empty on tablets (no printer).',
    save: 'Save',
    settingsSaved: 'Settings saved',
  },
};

export const CURRENCY = 'DA';
