import { Language } from './types';

export const CURRENCY = "DA";
export const APP_VERSION = "1.2.0";

export const TRANSLATIONS: Record<Language, any> = {
  fr: {
    dashboard: "Tableau de bord",
    production: "Production",
    inventory: "Inventaire",
    pos: "Point de vente",
    management: "Gestion",
    aiManager: "Manager IA",
    productManagement: "Gestion des produits",
    delivery: "Livraison",
    users: "Utilisateurs",
    reports: "Rapports",
    settings: "Paramètres",
    logout: "Déconnexion",
    activeBatches: "Lots actifs",
    expiryWatchlist: "Surveillance expiration",
    stockStatus: "État des stocks",
    suppliers: "Fournisseurs",
    customers: "Clients",
    totalSales: "Ventes totales",
    topSellers: "Meilleures ventes",
    recentOrders: "Commandes récentes",
    addBatch: "Ajouter un lot",
    startProduction: "Démarrer la production",
    completeProduction: "Terminer la production",
    cancelProduction: "Annuler la production",
    search: "Rechercher...",
    language: "Langue",
    french: "Français",
    arabic: "Arabe",
    name: "Nom",
    category: "Catégorie",
    price: "Prix",
    stock: "Stock",
    status: "Statut",
    actions: "Actions",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    quantity: "Quantité",
    total: "Total",
    checkout: "Payer",
    paymentMethod: "Mode de paiement",
    cash: "Espèces",
    card: "Carte",
    mobile: "Mobile",
    unit: "Unité",
    minStock: "Stock min",
    currentStock: "Stock actuel",
    ingredients: "Ingrédients",
    recipe: "Recette",
    product: "Produit",
    regular: "Produit de Vente",
    batchSize: "Taille du lot",
    prepTime: "Temps de prép",
    minutes: "minutes",
    hours: "heures",
    days: "jours",
    auditLog: "Journal d'audit",
    staffDirectory: "Répertoire du personnel",
    financialOverview: "Aperçu financier",
    salesTrends: "Tendances des ventes",
    welcome: "Bienvenue",
    login: "Connexion",
    loginWithGoogle: "Se connecter avec Google",
    description: "Description",
    specifications: "Spécifications",
    publicStore: "Boutique Clients",
    businessStore: "Boutique Business",
    b2bStore: "Boutique Business",
    orderStatus: "Statut de la commande",
    trackOrder: "Suivre la commande",
    assignDelivery: "Assigner la livraison",
    ordered: "Commandé",
    requested: "Demandé",
    none: "Aucune action",
    viennoiserie: "Viennoiserie",
    patisserie: "Pâtisserie",
    boulangerie: "Boulangerie",
    traiteur: "Traiteur",
    boissons: "Boissons",
    cooking: "Cuisine",
    maintenance: "Maintenance",
    cleaning: "Nettoyage",
    others: "Autres",
    inviteMember: "Inviter un membre",
    manageTeam: "Gérez votre équipe et les autorisations système",
    member: "Membre",
    role: "Rôle",
    joined: "Rejoint",
    securityOverview: "Aperçu de la sécurité",
    securityDescription: "Toutes les autorisations du système sont correctement configurées selon le Blueprint Artisanal.",
    admins: "Administrateurs",
    managers: "Managers",
    staff: "Personnel",
    viewFullHistory: "Voir l'historique complet",
    inviteTeamMember: "Inviter un membre de l'équipe",
    fullName: "Nom complet",
    emailAddress: "Adresse e-mail",
    sendInvite: "Envoyer l'invitation",
    deliveryStats: "Stats de livraison",
    activeDeliveries: "Livraisons actives",
    avgDeliveryTime: "Temps de livraison moyen",
    todayCompletions: "Terminés aujourd'hui",
    deliveryPersonnel: "Personnel de livraison",
    available: "Disponible",
    searchOrders: "Rechercher des commandes...",
    pending: "En attente",
    inProgress: "En cours",
    "in-progress": "En cours",
    planned: "Planifié",
    cancelled: "Annulé",
    allStatuses: 'Tous les statuts',
    inStock: 'En stock',
    outOfStock: 'Rupture de stock',
    resetFilters: 'Réinitialiser les filtres',
    manageCategories: 'Gérer les catégories',
    newCategoryName: 'Nom de la nouvelle catégorie',
    categoryAdded: 'Catégorie ajoutée avec succès',
    errorAddingCategory: 'Erreur lors de l\'ajout de la catégorie',
    productNameExists: 'Un produit avec ce nom existe déjà',
    cannotDeleteProductInUse: 'Impossible de supprimer un produit lié à un lot ou une commande en cours',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cet élément ?',
    createdBy: 'Créé par',
    allUsers: 'Tous les utilisateurs',
    unfulfilledOrders: 'Commandes non honorées',
    delayedOrders: 'Commandes retardées',
    last30Days: 'Les 30 derniers jours',
    totalAmount: 'Montant total',
    orderSummary: 'Résumé des commandes',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
    monthly: 'Mensuel',
    activities: 'Activités',
    userActivities: 'Activités de l\'utilisateur',
    action: 'Action',
    details: 'Détails',
    timestamp: 'Horodatage',
    allCategories: "Toutes les catégories",
    all: "Tout",
    filter: "Filtrer",
    reset: "Réinitialiser",
    delivered: "Livré",
    order: "Commande",
    deliveryAddress: "Adresse de livraison",
    customer: "Client",
    assignedTo: "Assigné à",
    assignDeliveryGuy: "Assigner un livreur",
    selectDeliveryPersonnel: "Sélectionner le personnel de livraison",
    markDelivered: "Marquer comme livré",
    orderDetails: "Détails de la commande",
    editUser: "Modifier l'utilisateur",
    updateUser: "Mettre à jour l'utilisateur",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    addTeamMember: "Ajouter un membre",
    addUser: "Ajouter l'utilisateur",
    weight: "Poids",
    imageUrl: "URL de l'image",
    notAvailable: "Non disponible",
    sellingPrice: "Prix de vente",
    costPrice: "Prix de revient",
    shelfLife: "Durée de conservation",
    editProduct: "Modifier le produit",
    addProduct: "Ajouter un produit",
    material: "Matière",
    orders: "Commandes",
    clientName: "Nom du client",
    deliveryType: "Type de livraison",
    expectedTime: "Heure prévue",
    expectedDate: "Date prévue",
    deliveryStatus: "Statut de livraison",
    rawMaterial: "Matière Première",
    rawMaterialManagement: "Gestion des matières premières",
    started: "Démarré",
    termination: "Terminaison",
    delayed: "Retardé",
    business: "Entreprise",
    reorder: "Réorganiser",
    profit: "Profit",
    costs: "Coûts",
    inventoryConsumption: "Consommation d'inventaire",
    percentage: "Pourcentage",
    frozen: "Congelé",
    rawMaterials: "Matières Premières",
    critical: "Critique",
    empty: "Vide",
    good: "Bon",
    medium: "Moyen",
    cardView: "Vue Carte",
    listView: "Vue Liste",
    darkMode: "Mode Sombre",
    systemAlerts: "Alertes Système",
    newOrderAlert: "Nouvelle commande en ligne !",
    calculatedFromIngredients: "Calculé à partir des ingrédients",
    updatesIngredientsAutomatically: "Met à jour les ingrédients automatiquement",
    maxPossible: "Maximum possible",
    insufficientStock: "Stock insuffisant",
    totalQuantity: "Quantité totale",
    selectMaterial: "Sélectionner une matière",
    addIngredient: "Ajouter un ingrédient",
    selectCategory: "Sélectionner une catégorie",
    uploadImage: "Télécharger une image",
    changeImage: "Changer l'image",
    inventoryDesc: "Gérez vos produits et matières premières",
    addMaterial: "Ajouter une matière",
    reorderSuggestions: "Suggestions de réapprovisionnement",
    hLife: "h de conservation",
    level: "Niveau",
    generalInfo: "Informations générales",
    artisanalRecipe: "Recette artisanale",
    selectIngredient: "Sélectionner un ingrédient",
    noRecipeDefined: "Aucune recette définie pour ce produit",
    createRecipe: "Créer une recette",
    inventoryStatus: "État de l'inventaire",
    stockHealth: "Santé du stock",
    optimal: "Optimal",
    artisanalTip: "Conseil artisanal",
    proInsight: "Aperçu pro",
    humidityCheck: "Vérifiez les niveaux d'humidité aujourd'hui.",
    flour: "Farine",
    dairy: "Produits laitiers",
    sugar: "Sucre",
    liquid: "Liquide",
    other: "Autre",
    units: "Unités",
    kg: "kg",
    g: "g",
    l: "l",
    ml: "ml",
    orderReport: "Rapport de commande",
    roleManagement: "Gestion des rôles",
    permissions: "Autorisations",
    allowedRoutes: "Routes autorisées",
    adminRoleImmutable: "Le rôle d'administrateur est immuable",
    manager: "Manager",
    cashier: "Caissier",
    baker: "Boulanger",
    delivery_guy: "Livreur",
    customer_business: "Client Business",
    customer_customers: "Client Customers",
    promotions: "Promotions",
    expiryDate: "Date d'expiration",
    isActive: "Actif",
    addPromotion: "Ajouter une promotion",
    pack: "Pack",
    isPack: "Est un pack",
    packItems: "Articles du pack",
    selectProduct: "Sélectionner un produit",
    noPromotions: "Aucune promotion active",
    day: "Jour",
    week: "Semaine",
    month: "Mois",
    year: "Année",
    batchCreatedSuccessfully: "Lot créé avec succès",
    batchStatusUpdated: "Statut du lot mis à jour",
    errorUpdatingBatchStatus: "Erreur lors de la mise à jour du statut du lot",
    errorCreatingBatch: "Erreur lors de la création du lot",
    productionStats: "Statistiques de production",
    batchDetails: "Détails du lot",
    editBatch: "Modifier le lot",
    updateBatch: "Mettre à jour le lot",
    orderStats: "Statistiques des commandes",
    cleanDatabase: "Nettoyer la base de données",
    confirmCleanDatabase: "Êtes-vous sûr de vouloir supprimer les produits en double ? Cette action est irréversible.",
    noDuplicatesFound: "Aucun produit en double trouvé.",
    duplicatesDeleted: "produits en double supprimés",
    databaseCleanedSuccess: "Nettoyage terminé : {deleted} doublons supprimés, {updated} matières mises à jour, permissions réinitialisées.",
    errorCleaningDatabase: "Erreur lors du nettoyage de la base de données",
    todaySales: "Ventes d'aujourd'hui",
    todayConsumption: "Consommation d'aujourd'hui",
    todayAccess: "Accès d'aujourd'hui",
    stockAlerts: "Alertes de stock",
    noSalesYet: "Aucune vente",
    lowStock: "Stock faible",
    activeUsers: "Utilisateurs actifs",
    addSupplier: "Ajouter un fournisseur",
    contactInfo: "Informations de contact",
    associatedMaterials: "Matières associées",
    invoiceHistory: "Historique des factures",
    phone: "Téléphone",
    address: "Adresse",
    email: "E-mail",
    supplierName: "Nom du fournisseur",
    editSupplier: "Modifier le fournisseur",
    supplierAdded: "Fournisseur ajouté avec succès",
    supplierUpdated: "Fournisseur mis à jour avec succès",
    supplierDeleted: "Fournisseur supprimé avec succès",
  },
  ar: {
    dashboard: "لوحة القيادة",
    production: "الإنتاج",
    inventory: "المخزون",
    pos: "نقطة البيع",
    management: "الإدارة",
    aiManager: "المدير الذكي",
    productManagement: "إدارة المنتجات",
    delivery: "التوصيل",
    users: "المستخدمين",
    reports: "التقارير",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    activeBatches: "الدفعات النشطة",
    expiryWatchlist: "مراقبة انتهاء الصلاحية",
    stockStatus: "حالة المخزون",
    suppliers: "الموردين",
    customers: "العملاء",
    totalSales: "إجمالي المبيعات",
    topSellers: "الأكثر مبيعاً",
    recentOrders: "الطلبات الأخيرة",
    addBatch: "إضافة دفعة",
    startProduction: "بدء الإنتاج",
    completeProduction: "إكمال الإنتاج",
    cancelProduction: "إلغاء الإنتاج",
    search: "بحث...",
    language: "اللغة",
    french: "الفرنسية",
    arabic: "العربية",
    name: "الاسم",
    category: "الفئة",
    price: "السعر",
    stock: "المخزون",
    status: "الحالة",
    actions: "الإجراءات",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    quantity: "الكمية",
    total: "الإجمالي",
    checkout: "دفع",
    paymentMethod: "طريقة الدفع",
    cash: "نقداً",
    card: "بطاقة",
    mobile: "هاتف",
    unit: "الوحدة",
    minStock: "الحد الأدنى",
    currentStock: "المخزون الحالي",
    ingredients: "المكونات",
    recipe: "الوصفة",
    product: "المنتج",
    regular: "منتج مبيعات",
    batchSize: "حجم الدفعة",
    prepTime: "وقت التحضير",
    minutes: "دقائق",
    hours: "ساعات",
    days: "أيام",
    auditLog: "سجل التدقيق",
    staffDirectory: "دليل الموظفين",
    financialOverview: "نظرة مالية",
    salesTrends: "اتجاهات المبيعات",
    welcome: "مرحباً",
    login: "تسجيل الدخول",
    loginWithGoogle: "الدخول بجوجل",
    description: "الوصف",
    specifications: "المواصفات",
    publicStore: "متجر العملاء",
    businessStore: "متجر الأعمال",
    b2bStore: "متجر الأعمال",
    orderStatus: "حالة الطلب",
    trackOrder: "تتبع الطلب",
    assignDelivery: "تعيين التوصيل",
    ordered: "تم الطلب",
    requested: "مطلوب",
    none: "لا يوجد إجراء",
    viennoiserie: "فطائر",
    patisserie: "حلويات",
    boulangerie: "مخبوزات",
    traiteur: "مأكولات جاهزة",
    boissons: "مشروبات",
    cooking: "طبخ",
    maintenance: "صيانة",
    cleaning: "تنظيف",
    others: "أخرى",
    inviteMember: "دعوة عضو",
    manageTeam: "إدارة فريقك وأذونات النظام",
    member: "عضو",
    role: "الدور",
    joined: "انضم في",
    securityOverview: "نظرة عامة على الأمان",
    securityDescription: "تم تكوين جميع أذونات النظام بشكل صحيح وفقاً للمخطط الحرفي.",
    admins: "المسؤولين",
    managers: "المديرين",
    staff: "الموظفين",
    viewFullHistory: "عرض السجل الكامل",
    inviteTeamMember: "دعوة عضو للفريق",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    sendInvite: "إرسال الدعوة",
    deliveryStats: "إحصائيات التوصيل",
    activeDeliveries: "عمليات التوصيل النشطة",
    avgDeliveryTime: "متوسط وقت التوصيل",
    todayCompletions: "عمليات الإكمال اليوم",
    deliveryPersonnel: "موظفي التوصيل",
    available: "متاح",
    searchOrders: "البحث في الطلبات...",
    pending: "قيد الانتظار",
    inProgress: "قيد التنفيذ",
    "in-progress": "قيد التنفيذ",
    planned: "مخطط",
    cancelled: "ملغى",
    allStatuses: 'جميع الحالات',
    inStock: 'في المخزن',
    outOfStock: 'نفد من المخزن',
    resetFilters: 'إعادة ضبط الفلاتر',
    manageCategories: 'إدارة الفئات',
    newCategoryName: 'اسم الفئة الجديدة',
    categoryAdded: 'تم إضافة الفئة بنجاح',
    errorAddingCategory: 'خطأ في إضافة الفئة',
    productNameExists: 'يوجد منتج بهذا الاسم بالفعل',
    cannotDeleteProductInUse: 'لا يمكن حذف منتج مرتبط بدفعة أو طلب قيد التنفيذ',
    confirmDelete: 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
    createdBy: 'أنشئت بواسطة',
    allUsers: 'جميع المستخدمين',
    unfulfilledOrders: 'الطلبات غير المستوفاة',
    delayedOrders: 'الطلبات المتأخرة',
    last30Days: 'آخر 30 يومًا',
    totalAmount: 'المبلغ الإجمالي',
    orderSummary: 'ملخص الطلبات',
    daily: 'يومي',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    activities: 'الأنشطة',
    userActivities: 'أنشطة المستخدم',
    action: 'إجراء',
    details: 'تفاصيل',
    timestamp: 'طابع زمني',
    allCategories: "جميع الفئات",
    all: "الكل",
    filter: "تصفية",
    reset: "إعادة تعيين",
    delivered: "تم التوصيل",
    order: "طلب",
    deliveryAddress: "عنوان التوصيل",
    customer: "العميل",
    assignedTo: "مكلف بـ",
    assignDeliveryGuy: "تعيين عامل توصيل",
    selectDeliveryPersonnel: "اختر موظف التوصيل",
    markDelivered: "تحديد كمكتمل",
    orderDetails: "تفاصيل الطلب",
    editUser: "تعديل المستخدم",
    updateUser: "تحديث المستخدم",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    addTeamMember: "إضافة عضو للفريق",
    addUser: "إضافة مستخدم",
    weight: "الوزن",
    imageUrl: "رابط الصورة",
    notAvailable: "غير متوفر",
    sellingPrice: "سعر البيع",
    costPrice: "سعر التكلفة",
    shelfLife: "مدة الصلاحية",
    editProduct: "تعديل المنتج",
    addProduct: "إضافة منتج",
    material: "المادة",
    orders: "الطلبات",
    clientName: "اسم العميل",
    deliveryType: "نوع التوصيل",
    expectedTime: "الوقت المتوقع",
    expectedDate: "التاريخ المتوقع",
    deliveryStatus: "حالة التوصيل",
    rawMaterial: "مواد خام",
    rawMaterialManagement: "إدارة المواد الخام",
    started: "بدأ",
    termination: "إنهاء",
    delayed: "متأخر",
    business: "عمل",
    reorder: "إعادة طلب",
    profit: "الربح",
    costs: "التكاليف",
    inventoryConsumption: "استهلاك المخزون",
    percentage: "نسبة مئوية",
    frozen: "مجمد",
    rawMaterials: "المواد الخام",
    critical: "حرج",
    empty: "فارغ",
    good: "جيد",
    medium: "متوسط",
    cardView: "عرض البطاقات",
    listView: "عرض القائمة",
    darkMode: "الوضع الداكن",
    systemAlerts: "تنبيهات النظام",
    newOrderAlert: "طلب جديد عبر الإنترنت!",
    calculatedFromIngredients: "محسوب من المكونات",
    updatesIngredientsAutomatically: "تحديث المكونات تلقائياً",
    maxPossible: "الحد الأقصى الممكن",
    insufficientStock: "مخزون غير كافٍ",
    totalQuantity: "الكمية الإجمالية",
    selectMaterial: "اختر المادة",
    addIngredient: "إضافة مكون",
    selectCategory: "اختر الفئة",
    uploadImage: "رفع صورة",
    changeImage: "تغيير الصورة",
    inventoryDesc: "إدارة المنتجات والمواد الخام الخاصة بك",
    addMaterial: "إضافة مادة",
    reorderSuggestions: "اقتراحات إعادة الطلب",
    hLife: "ساعة صلاحية",
    level: "المستوى",
    generalInfo: "معلومات عامة",
    artisanalRecipe: "وصفة حرفية",
    selectIngredient: "اختر المكون",
    noRecipeDefined: "لا توجد وصفة محددة لهذا المنتج",
    createRecipe: "إنشاء وصفة",
    inventoryStatus: "حالة المخزون",
    stockHealth: "صحة المخزون",
    optimal: "مثالي",
    artisanalTip: "نصيحة حرفية",
    proInsight: "رؤية احترافية",
    humidityCheck: "تحقق من مستويات الرطوبة اليوم.",
    flour: "دقيق",
    dairy: "ألبان",
    sugar: "سكر",
    liquid: "سائل",
    other: "آخر",
    units: "وحدات",
    kg: "كجم",
    g: "جم",
    l: "لتر",
    ml: "مل",
    orderReport: "تقرير الطلبات",
    roleManagement: "إدارة الأدوار",
    permissions: "الأذونات",
    allowedRoutes: "المسارات المسموح بها",
    adminRoleImmutable: "دور المسؤول غير قابل للتغيير",
    manager: "مدير",
    cashier: "كاشير",
    baker: "خباز",
    delivery_guy: "عامل توصيل",
    customer_business: "عميل أعمال",
    customer_customers: "عميل عادي",
    promotions: "العروض",
    expiryDate: "تاريخ الانتهاء",
    isActive: "نشط",
    addPromotion: "إضافة عرض",
    pack: "حزمة",
    isPack: "هل هي حزمة",
    packItems: "عناصر الحزمة",
    selectProduct: "اختر منتجاً",
    noPromotions: "لا توجد عروض نشطة",
    day: "يوم",
    week: "أسبوع",
    month: "شهر",
    year: "سنة",
    batchCreatedSuccessfully: "تم إنشاء الدفعة بنجاح",
    batchStatusUpdated: "تم تحديث حالة الدفعة",
    errorUpdatingBatchStatus: "خطأ في تحديث حالة الدفعة",
    errorCreatingBatch: "خطأ في إنشاء الدفعة",
    productionStats: "إحصائيات الإنتاج",
    batchDetails: "تفاصيل الدفعة",
    editBatch: "تعديل الدفعة",
    updateBatch: "تحديث الدفعة",
    orderStats: "إحصائيات الطلبات",
    cleanDatabase: "تنظيف قاعدة البيانات",
    confirmCleanDatabase: "هل أنت متأكد أنك تريد حذف المنتجات المكررة؟ هذا الإجراء لا يمكن التراجع عنه.",
    noDuplicatesFound: "لم يتم العثور على منتجات مكررة.",
    duplicatesDeleted: "منتجات مكررة تم حذفها",
    databaseCleanedSuccess: "اكتمل التنظيف: تم حذف {deleted} مكررات، وتحديث {updated} مواد، وإعادة تعيين الأذونات.",
    errorCleaningDatabase: "خطأ أثناء تنظيف قاعدة البيانات",
    todaySales: "مبيعات اليوم",
    todayConsumption: "استهلاك اليوم",
    todayAccess: "دخول اليوم",
    stockAlerts: "تنبيهات المخزون",
    noSalesYet: "لا توجد مبيعات",
    lowStock: "مخزون منخفض",
    activeUsers: "المستخدمين النشطين",
    addSupplier: "إضافة مورد",
    contactInfo: "معلومات الاتصال",
    associatedMaterials: "المواد المرتبطة",
    invoiceHistory: "سجل الفواتير",
    phone: "الهاتف",
    address: "العنوان",
    email: "البريد الإلكتروني",
    supplierName: "اسم المورد",
    editSupplier: "تعديل المورد",
    supplierAdded: "تم إضافة المورد بنجاح",
    supplierUpdated: "تم تحديث المورد بنجاح",
    supplierDeleted: "تم حذف المورد بنجاح",
  },
};

export const PCN_ACCOUNTS = [
  // 1000–1999 ACTIFS
  { number: '1100', name: 'Disponibilités', type: 'ACTIF', isCategory: true, normalBalance: 'DÉBIT' },
  { number: '1101', name: 'Caisse Principale', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '1102', name: 'Petite Caisse', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '1103', name: 'Banque - Compte Courant', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '1200', name: 'Créances Clients', type: 'ACTIF', isCategory: true, normalBalance: 'DÉBIT' },
  { number: '1201', name: 'Clients Particuliers', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '1202', name: 'Clients B2B / Grossistes', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '1300', name: 'Stocks', type: 'ACTIF', isCategory: true, normalBalance: 'DÉBIT' },
  { number: '1301', name: 'Matières Premières', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '1303', name: 'Produits Finis', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '1500', name: 'Immobilisations Corporelles', type: 'ACTIF', isCategory: true, normalBalance: 'DÉBIT' },
  { number: '1501', name: 'Matériel Boulangerie', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  
  // 2000–2999 PASSIFS
  { number: '2100', name: 'Fournisseurs', type: 'PASSIF', isCategory: true, normalBalance: 'CRÉDIT' },
  { number: '2101', name: 'Fournisseurs - Matières Premières', type: 'PASSIF', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '2200', name: 'Charges à Payer', type: 'PASSIF', isCategory: true, normalBalance: 'CRÉDIT' },
  { number: '2201', name: 'Salaires à Payer', type: 'PASSIF', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '2203', name: 'CNAS Patronale à Payer (26%)', type: 'PASSIF', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '2204', name: 'CNAS Salariale à Payer (9%)', type: 'PASSIF', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '2205', name: 'IRG sur Salaires à Verser', type: 'PASSIF', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '2300', name: 'Obligations Fiscales', type: 'PASSIF', isCategory: true, normalBalance: 'CRÉDIT' },
  { number: '2301', name: 'TVA Collectée', type: 'PASSIF', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '2302', name: 'TVA Déductible', type: 'ACTIF', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '2303', name: 'TAP à Payer (2%)', type: 'PASSIF', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '2304', name: 'IBS à Payer', type: 'PASSIF', isCategory: false, normalBalance: 'CRÉDIT' },

  // 3000–3999 CAPITAUX
  { number: '3001', name: 'Capital Social', type: 'CAPITAUX', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '3003', name: 'Résultat de l\'Exercice', type: 'CAPITAUX', isCategory: false, normalBalance: 'CRÉDIT' },

  // 4000–4999 PRODUITS
  { number: '4001', name: 'Ventes - Pain', type: 'PRODUIT', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '4002', name: 'Ventes - Viennoiserie', type: 'PRODUIT', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '4003', name: 'Ventes - Pâtisseries', type: 'PRODUIT', isCategory: false, normalBalance: 'CRÉDIT' },
  { number: '4006', name: 'Ventes - B2B', type: 'PRODUIT', isCategory: false, normalBalance: 'CRÉDIT' },

  // 5000–5999 CMV
  { number: '5001', name: 'Consommation Matières Premières', type: 'CMV', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '5003', name: 'Main d\'Œuvre Directe', type: 'CMV', isCategory: false, normalBalance: 'DÉBIT' },

  // 6000–6999 CHARGES
  { number: '6001', name: 'Salaires - Administration', type: 'CHARGE', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '6003', name: 'Charges Sociales Patronales CNAS', type: 'CHARGE', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '6004', name: 'Loyer', type: 'CHARGE', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '6005', name: 'Électricité et Gaz', type: 'CHARGE', isCategory: false, normalBalance: 'DÉBIT' },
  { number: '6014', name: 'TAP (2% du CA HT)', type: 'CHARGE', isCategory: false, normalBalance: 'DÉBIT' },
];

export const FINANCIAL_TRANSLATIONS: Record<Language, any> = {
  fr: {
    finance: "Finance",
    generalLedger: "Grand Livre",
    payroll: "Paie",
    expenses: "Dépenses",
    revenue: "Revenus",
    taxReports: "Rapports Fiscaux",
    riskEngine: "Moteur de Risque",
    budgeting: "Budgétisation",
    assets: "Immobilisations",
    cashFlow: "Flux de Trésorerie",
    journalEntries: "Écritures de Journal",
    newEntry: "Nouvelle Écriture",
    account: "Compte",
    debit: "Débit",
    credit: "Crédit",
    balance: "Solde",
    period: "Période",
    employee: "Employé",
    baseSalary: "Salaire de Base",
    netSalary: "Salaire Net",
    grossSalary: "Salaire Brut",
    cnas: "CNAS",
    irg: "IRG",
    payslip: "Bulletin de Paie",
    runPayroll: "Lancer la Paie",
    supplierInvoices: "Factures Fournisseurs",
    customerInvoices: "Factures Clients",
    riskScore: "Score de Risque",
    riskLevel: "Niveau de Risque",
    low: "Faible",
    moderate: "Modéré",
    high: "Élevé",
    critical: "Critique",
    cashRunway: "Autonomie Trésorerie",
    days: "jours",
    cogsRate: "Taux COGS",
    payrollRate: "Taux Masse Salariale",
    taxCalendar: "Calendrier Fiscal",
    nextDeadline: "Prochaine Échéance",
    g50: "Déclaration G50",
    ibs: "IBS",
    tap: "TAP",
    tva: "TVA",
    reconciliation: "Rapprochement",
    physicalCash: "Espèces Physiques",
    systemCash: "Espèces Système",
    discrepancy: "Écart",
    reconcile: "Rapprocher",
  },
  ar: {
    finance: "المالية",
    generalLedger: "دفتر الأستاذ العام",
    payroll: "الرواتب",
    expenses: "المصاريف",
    revenue: "الإيرادات",
    taxReports: "التقارير الضريبية",
    riskEngine: "محرك المخاطر",
    budgeting: "الميزانية",
    assets: "الأصول",
    cashFlow: "التدفق النقدي",
    journalEntries: "قيود اليومية",
    newEntry: "قيد جديد",
    account: "الحساب",
    debit: "مدين",
    credit: "دائن",
    balance: "الرصيد",
    period: "الفترة",
    employee: "الموظف",
    baseSalary: "الراتب الأساسي",
    netSalary: "الراتب الصافي",
    grossSalary: "الراتب الإجمالي",
    cnas: "الضمان الاجتماعي",
    irg: "الضريبة على الدخل",
    payslip: "قسيمة الراتب",
    runPayroll: "تشغيل الرواتب",
    supplierInvoices: "فواتير الموردين",
    customerInvoices: "فواتير العملاء",
    riskScore: "درجة المخاطر",
    riskLevel: "مستوى المخاطر",
    low: "منخفض",
    moderate: "متوسط",
    high: "مرتفع",
    critical: "حرج",
    cashRunway: "استقلالية الخزينة",
    days: "أيام",
    cogsRate: "معدل تكلفة المبيعات",
    payrollRate: "معدل كتلة الأجور",
    taxCalendar: "التقويم الضريبي",
    nextDeadline: "الموعد النهائي القادم",
    g50: "تصريح G50",
    ibs: "ضريبة الشركات",
    tap: "الضريبة المهنية",
    tva: "الضريبة على القيمة المضافة",
    reconciliation: "تسوية",
    physicalCash: "النقد الفعلي",
    systemCash: "النقد في النظام",
    discrepancy: "الفارق",
    reconcile: "تسوية",
  }
};

export const PRODUCT_NAMES: Record<Language, Record<string, string>> = {
  fr: {
    'Croissant au Beurre': 'Croissant au Beurre',
    'Pain au Chocolat': 'Pain au Chocolat',
    'Macarons Assortis (6pcs)': 'Macarons Assortis (6pcs)',
    'Baguette Tradition': 'Baguette Tradition',
    'Éclair au Chocolat': 'Éclair au Chocolat',
    'Tarte aux Fraises': 'Tarte aux Fraises',
    'Pain aux Raisins': 'Pain aux Raisins',
    'Croissant aux Amandes': 'Croissant aux Amandes',
    'Paris-Brest': 'Paris-Brest',
    'Mille-Feuille': 'Mille-Feuille',
    'Farine T55': 'Farine T55',
    'Beurre AOP': 'Beurre AOP',
    'Chocolat Noir 70%': 'Chocolat Noir 70%',
    'Sucre Cristal': 'Sucre Cristal',
    'Levure Boulangère': 'Levure Boulangère',
    'Lait Entier': 'Lait Entier',
    'Milk': 'Lait',
    'Flour': 'Farine',
    'Sugar': 'Sucre',
    'Butter': 'Beurre',
    'Water': 'Eau',
    'Yeast': 'Levure',
    'Chocolate': 'Chocolat',
  },
  ar: {
    'Croissant au Beurre': 'كرواسون بالزبدة',
    'Pain au Chocolat': 'خبز بالشوكولاتة',
    'Macarons Assortis (6pcs)': 'ماكرون مشكل (6 قطع)',
    'Baguette Tradition': 'باجيت تقليدي',
    'Éclair au Chocolat': 'إكلير بالشوكولاتة',
    'Tarte aux Fraises': 'تارت الفراولة',
    'Pain aux Raisins': 'خبز بالزبيب',
    'Croissant aux Amandes': 'كرواسون باللوز',
    'Paris-Brest': 'باريس بريست',
    'Mille-Feuille': 'ميل فوي',
    'Farine T55': 'دقيق T55',
    'Beurre AOP': 'زبدة AOP',
    'Chocolat Noir 70%': 'شوكولاتة داكنة 70%',
    'Sucre Cristal': 'سكر كريستال',
    'Levure Boulangère': 'خميرة الخباز',
    'Lait Entier': 'حليب كامل الدسم',
    'Milk': 'حليب',
    'Flour': 'دقيق',
    'Sugar': 'سكر',
    'Butter': 'زبدة',
    'Water': 'ماء',
    'Yeast': 'خميرة',
    'Chocolate': 'شوكولاتة',
  }
};

export const CATEGORY_NAMES: Record<Language, Record<string, string>> = {
  fr: {
    'viennoiserie': 'Viennoiserie',
    'patisserie': 'Pâtisserie',
    'boulangerie': 'Boulangerie',
    'traiteur': 'Traiteur',
    'boissons': 'Boissons',
    'cooking': 'Cuisine',
    'maintenance': 'Maintenance',
    'cleaning': 'Nettoyage',
    'others': 'Autres',
    'raw_material': 'Matière Première',
    'flour': 'Farine',
    'dairy': 'Produits Laitiers',
    'sugar': 'Sucre',
    'liquid': 'Liquide',
    'other_material': 'Autre Matière',
  },
  ar: {
    'viennoiserie': 'فينوازيري',
    'patisserie': 'حلويات',
    'boulangerie': 'مخبوزات',
    'traiteur': 'خدمات طعام',
    'boissons': 'مشروبات',
    'cooking': 'طبخ',
    'maintenance': 'صيانة',
    'cleaning': 'تنظيف',
    'others': 'أخرى',
    'raw_material': 'مواد خام',
    'flour': 'دقيق',
    'dairy': 'ألبان',
    'sugar': 'سكر',
    'liquid': 'سوائل',
    'other_material': 'مواد أخرى',
  }
};

export const CATEGORIES = [
  "viennoiserie",
  "patisserie",
  "boulangerie",
  "traiteur",
  "boissons",
  "cooking",
  "maintenance",
  "cleaning",
  "others",
  "raw_material",
  "flour",
  "dairy",
  "sugar",
  "liquid",
  "other_material"
];

export const UNITS = [
  "kg",
  "g",
  "l",
  "ml",
  "pcs",
  "unit"
];
